### PR TITLE
add more sophisticated algorithm for digital rain

### PR DESCRIPTION
**Pull request by pintosum**

### CODE REVIEW

**Comment by tamton-aquib** [comment]
Really cool, hey @pintosum can you change the branch to main? I think dev is 2 commits behind and I havent worked on this repo for a long time

**Comment by pintosum** [comment]
Forgot to mention that it requires utf-8 encoding module installed for Neovim's LuaJIT, namely this: https://github.com/uga-rosa/utf8.nvim. Just for generating some neat Japanese symbols.

**Comment by pintosum** [comment]
@tamton-aquib Well, it's ready to go

**Comment by tamton-aquib** [comment]
Really cool ❤️ 
The offset at the beginning looks a bit weird but its much much better than what was before.

Thanks, by the way

**Pull request merged**
